### ISSUE TITLE
`npx firebase use --add` empty

### ISSUE THREAD

**Issue by davidnash** [kefranabg/bento-starter#174]
**Describe the bug**
"Which project do you want to add?" is empty. When I hit enter I get:
`Error: An unexpected error has occurred.`

**To Reproduce**
I'm following the install instructions here: https://bento-starter.netlify.com/setup/#step-2-firebase-configuration

The step `npx firebase use --add` shows an empty list (with "(Use arrow keys)".

**firebase-debug.log**
```
[debug] [2019-05-21T05:25:59.294Z] ----------------------------------------------------------------------
[debug] [2019-05-21T05:25:59.295Z] Command:       /usr/bin/node /home/david/wordlist/node_modules/.bin/firebase use --add
[debug] [2019-05-21T05:25:59.296Z] CLI Version:   6.9.2
[debug] [2019-05-21T05:25:59.296Z] Platform:      linux
[debug] [2019-05-21T05:25:59.296Z] Node Version:  v12.2.0
[debug] [2019-05-21T05:25:59.296Z] Time:          Tue May 21 2019 15:25:59 GMT+1000 (Australian Eastern Standard Time)
[debug] [2019-05-21T05:25:59.296Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-05-21T05:25:59.301Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-05-21T05:25:59.301Z] > authorizing via signed-in user
[debug] [2019-05-21T05:25:59.302Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects  
 
[debug] [2019-05-21T05:26:00.691Z] <<< HTTP RESPONSE 200
[debug] [2019-05-21T05:26:01.968Z] TypeError: Cannot read property 'short' of undefined
    at Prompt.render (/home/david/wordlist/node_modules/firebase-tools/node_modules/inquirer/lib/prompts/list.js:94:69)
    at Prompt.onSubmit (/home/david/wordlist/node_modules/firebase-tools/node_modules/inquirer/lib/prompts/list.js:116:8)
...
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
- npm/npx 6.9.0

**Comment by kefranabg** [comment]
Hi @davidnash,

Did you create the firebase project in the [firebase console](https://console.firebase.google.com/u/0/) ?
Did you select the correct account after running `npx firebase login` ? (You have to select the account you used to create the firebase project)

**Comment by davidnash** [comment]
Thanks for your help @kefranabg ...

I'd created the firebase project under a different account! Feeling a little silly. Sorry about that.
