### ISSUE TITLE
Windows Setup Problems

### ISSUE THREAD

**Issue by hcmlopes** [kefranabg/bento-starter#224]
**Describe the bug**
Running `npm run setup` error with a bunch of the errors below
```
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\hcmlo\Documents\Work\projects\textloop\node_modules\.staging\@types\lodash-b2c07a52\ts3.1\fp\zipWith.d.ts'
```
Here are the 2 logs output.

[2019-12-02T15_21_44_116Z-debug.log](https://github.com/kefranabg/bento-starter/files/3911935/2019-12-02T15_21_44_116Z-debug.log)
[2019-12-02T15_21_04_245Z-debug.log](https://github.com/kefranabg/bento-starter/files/3911936/2019-12-02T15_21_04_245Z-debug.log)

running npm install and then npm run setup will complete the install.
At this point npx will no longer work and error out when `npx firebase login`
```
internal/modules/cjs/loader.js:305
      throw err;
      ^

Error: Cannot find module 'C:\Users\hcmlo\AppData\Roaming\npm\node_modules\npx\node_modules\libnpx\index.js'. Please verify that the package.json has a valid 
"main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\hcmlo\AppData\Roaming\npm\node_modules\npx\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\hcmlo\\AppData\\Roaming\\npm\\node_modules\\npx\\node_modules\\libnpx\\package.json',
  requestPath: 'libnpx'
}
```

**Comment by tbetous** [comment]
Did you install npx globally via the command `npm i -g npx` before using `npx firebase login` ?

**Comment by hcmlopes** [comment]
> Did you install npx globally via the command `npm i -g npx` before using `npx firebase login` ?

I did, at first it wan't working but then after messing with clearing cache and a whole bunch of other things npx did work again. Then once I started a frets project folder and ran setup and got things installed npx wouldn't work again

**Comment by tbetous** [comment]
Hi @hcmlopes ! Can you try to use this command `npx firebase login --interactive` instead of `npx firebase login` ?

**Comment by kefranabg** [comment]
Closing the issue: thread seems inactive.
